/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameOverView from "./scripts/GameOverView"
import GameManager from "./scripts/GameManager"
import CheckWarning from "./scripts/CheckWarning"
import CheckGameOver from "./scripts/CheckGameOver"
import FixScreen from "./scripts/FixScreen"
import Guide from "./scripts/Guide"
import Fruit from "./scripts/Fruit"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("scripts/GameOverView.js",GameOverView);
		reg("scripts/GameManager.js",GameManager);
		reg("scripts/CheckWarning.js",CheckWarning);
		reg("scripts/CheckGameOver.js",CheckGameOver);
		reg("scripts/FixScreen.js",FixScreen);
		reg("scripts/Guide.js",Guide);
		reg("scripts/Fruit.js",Fruit);
    }
}
GameConfig.width = 750;
GameConfig.height = 1624;
GameConfig.scaleMode ="fixedwidth";
GameConfig.screenMode = "vertical";
GameConfig.alignV = "middle";
GameConfig.alignH = "center";
GameConfig.startScene = "Main.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
