/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import Soundbtn from "./game/scripts/component/button/Soundbtn"
import VibrateBtn from "./game/scripts/component/button/VibrateBtn"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="views/game.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("game/scripts/component/button/Soundbtn.ts",Soundbtn);
        reg("game/scripts/component/button/VibrateBtn.ts",VibrateBtn);
    }
}
GameConfig.init();